# Use postgres/example user/password credentials
version: '3.1'

services:
  pdb:
    image: postgres:alpine
    restart: always
    container_name: 'postgresql'
    environment:
      POSTGRES_PASSWORD: 'top'
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
