# Use postgres/example user/password credentials
version: '3.1'

services:
  pdb:
    image: postgres:alpine
    restart: always
    container_name: 'postgresql'
    environment:
      POSTGRES_PASSWORD: top
    ports:
      - 54320:5432
    volumes:
      - psql_data:/var/lib/postgresql/data
volumes:
  psql_data:
